#!/usr/bin/env bash
# bootloader.sh — GRUB installation, os-prober, dual-boot
source "${LIB_DIR}/protection.sh"

# bootloader_install — Install and configure GRUB
bootloader_install() {
    einfo "Installing bootloader (GRUB)..."

    # Install GRUB
    try "Installing GRUB" emerge --quiet sys-boot/grub

    # Install os-prober for dual-boot detection
    if [[ "${WINDOWS_DETECTED:-0}" == "1" ]] || [[ "${ESP_REUSE:-no}" == "yes" ]]; then
        try "Installing os-prober" emerge --quiet sys-boot/os-prober
    fi

    # Install GRUB to ESP
    local grub_target="/efi"
    local grub_id="Gentoo"

    try "Installing GRUB to ESP" \
        grub-install --target=x86_64-efi --efi-directory="${grub_target}" \
        --bootloader-id="${grub_id}" --recheck

    # Configure GRUB
    _configure_grub

    # Generate GRUB config
    try "Generating GRUB configuration" grub-mkconfig -o /boot/grub/grub.cfg

    einfo "Bootloader installation complete"
}

# _configure_grub — Set up /etc/default/grub
_configure_grub() {
    einfo "Configuring GRUB..."

    local grub_default="/etc/default/grub"
    local root_uuid
    root_uuid=$(get_uuid "${ROOT_PARTITION}")

    local root_param=""
    if [[ -n "${root_uuid}" ]]; then
        root_param="root=UUID=${root_uuid}"
    else
        root_param="root=${ROOT_PARTITION}"
    fi

    # Add filesystem-specific parameters
    local extra_params=""
    if [[ "${FILESYSTEM:-ext4}" == "btrfs" ]]; then
        extra_params="rootflags=subvol=@"
    fi

    cat > "${grub_default}" << GRUBEOF
# /etc/default/grub
# Generated by ${INSTALLER_NAME} v${INSTALLER_VERSION}

GRUB_DEFAULT=0
GRUB_TIMEOUT=5
GRUB_TIMEOUT_STYLE=menu
GRUB_DISTRIBUTOR="Gentoo"

GRUB_CMDLINE_LINUX_DEFAULT="quiet loglevel=3"
GRUB_CMDLINE_LINUX="${extra_params}"

# Console settings
GRUB_TERMINAL_INPUT="console"
GRUB_TERMINAL_OUTPUT="gfxterm"
GRUB_GFXMODE="auto"
GRUB_GFXPAYLOAD_LINUX="keep"
GRUBEOF

    # Dual-boot: enable os-prober
    if [[ "${WINDOWS_DETECTED:-0}" == "1" ]] || [[ "${ESP_REUSE:-no}" == "yes" ]]; then
        cat >> "${grub_default}" << DUALEOF

# Dual-boot: os-prober enabled
GRUB_DISABLE_OS_PROBER=false
DUALEOF
        einfo "os-prober enabled for dual-boot detection"
    fi

    einfo "GRUB configured"
}
