#!/usr/bin/env bash
# portage.sh — Generate make.conf, select profile, sync repository
source "${LIB_DIR}/protection.sh"

# generate_make_conf — Create /etc/portage/make.conf with layered settings
generate_make_conf() {
    einfo "Generating make.conf..."

    if [[ "${DRY_RUN}" == "1" ]]; then
        einfo "[DRY-RUN] Would generate make.conf"
        _print_make_conf
        return 0
    fi

    local make_conf="${MOUNTPOINT}/etc/portage/make.conf"
    mkdir -p "$(dirname "${make_conf}")"
    _write_make_conf > "${make_conf}"

    einfo "make.conf generated at ${make_conf}"
}

# _print_make_conf — Print make.conf content (for dry-run / debug)
_print_make_conf() {
    _write_make_conf
}

# _write_make_conf — Generate make.conf content
_write_make_conf() {
    local march="${CPU_MARCH:-x86-64}"
    local jobs="${EMERGE_JOBS_DEFAULT}"
    local load="${EMERGE_LOAD_DEFAULT}"

    # Auto-calculate jobs from CPU count
    local cpu_count
    cpu_count=$(get_cpu_count)
    if (( cpu_count > 1 )); then
        jobs="${cpu_count}"
        load="${cpu_count}.0"
    fi

    local use_flags
    use_flags=$(get_use_flags "${INIT_SYSTEM:-systemd}" "${GPU_VENDOR:-}")

    cat << MAKECONF
# /etc/portage/make.conf
# Generated by ${INSTALLER_NAME} v${INSTALLER_VERSION}
# $(date -Iseconds)

# --- Compiler flags ---
COMMON_FLAGS="-march=${march} -O2 -pipe"
CFLAGS="\${COMMON_FLAGS}"
CXXFLAGS="\${COMMON_FLAGS}"
FCFLAGS="\${COMMON_FLAGS}"
FFLAGS="\${COMMON_FLAGS}"

# --- CPU flags ---
$(if [[ -n "${CPU_FLAGS:-}" ]]; then
    echo "CPU_FLAGS_X86=\"${CPU_FLAGS}\""
else
    echo "# CPU_FLAGS_X86 will be set after running cpuid2cpuflags in chroot"
    echo "# CPU_FLAGS_X86=\"\""
fi)

# --- Parallelism ---
MAKEOPTS="-j${jobs} -l${load}"
EMERGE_DEFAULT_OPTS="--jobs=${jobs} --load-average=${load} --with-bdeps=y --complete-graph=y"

# --- USE flags ---
USE="${use_flags}"

# --- Video ---
VIDEO_CARDS="${VIDEO_CARDS:-fbdev}"

# --- Input devices ---
INPUT_DEVICES="libinput"

# --- Accept licenses ---
ACCEPT_LICENSE="*"

# --- Mirrors ---
GENTOO_MIRRORS="${MIRROR_URL:-https://distfiles.gentoo.org}"

# --- GRUB ---
GRUB_PLATFORMS="${GRUB_PLATFORMS}"

# --- Portage features ---
FEATURES="parallel-fetch candy buildpkg"

# --- Language ---
L10N="$(echo "${LOCALE:-en_US.UTF-8}" | cut -d. -f1 | tr '_' '-' | tr '[:upper:]' '[:lower:]') en"
LINGUAS="$(echo "${LOCALE:-en_US.UTF-8}" | cut -d_ -f1) en"
MAKECONF
}

# portage_sync — Initial portage tree sync
portage_sync() {
    einfo "Syncing Portage repository..."

    # First sync with emerge-webrsync (faster initial download)
    try "Running emerge-webrsync" emerge-webrsync

    # Then update with emerge --sync
    try "Running emerge --sync" emerge --sync

    einfo "Portage tree synced"
}

# portage_select_profile — Select the appropriate eselect profile
portage_select_profile() {
    einfo "Selecting Portage profile..."

    local target_profile
    case "${INIT_SYSTEM:-systemd}" in
        systemd) target_profile="${PROFILE_SYSTEMD_DESKTOP}" ;;
        openrc)  target_profile="${PROFILE_OPENRC_DESKTOP}" ;;
    esac

    # Find the profile number
    local profile_num
    profile_num=$(eselect profile list | grep -n "${target_profile}" | head -1 | cut -d: -f1)

    if [[ -z "${profile_num}" ]]; then
        # Try partial match
        profile_num=$(eselect profile list | grep -n "plasma" | grep "${INIT_SYSTEM:-systemd}" | head -1 | cut -d: -f1)
    fi

    if [[ -z "${profile_num}" ]]; then
        ewarn "Could not find exact profile. Available profiles:"
        eselect profile list
        ewarn "Please select manually."

        local manual
        manual=$(eselect profile list | grep -n "desktop" | head -20)
        die "Profile selection failed. Available desktop profiles:\n${manual}"
    fi

    # eselect uses 1-based indexing from brackets [N]
    local profile_idx
    profile_idx=$(eselect profile list | grep "${target_profile}" | sed 's/.*\[//;s/\].*//' | head -1)

    if [[ -n "${profile_idx}" ]]; then
        try "Setting profile to ${target_profile}" \
            eselect profile set "${profile_idx}"
        einfo "Profile set to: ${target_profile}"
    else
        ewarn "Could not auto-select profile, attempting by name"
        try "Setting profile" eselect profile set "${target_profile}"
    fi
}

# portage_install_cpuflags — Install and run cpuid2cpuflags
portage_install_cpuflags() {
    if [[ -n "${CPU_FLAGS:-}" ]]; then
        einfo "CPU_FLAGS already set: ${CPU_FLAGS}"
        return 0
    fi

    try "Installing cpuid2cpuflags" emerge --quiet app-portage/cpuid2cpuflags

    CPU_FLAGS=$(cpuid2cpuflags 2>/dev/null | sed 's/CPU_FLAGS_X86: //') || CPU_FLAGS=""

    if [[ -n "${CPU_FLAGS}" ]]; then
        einfo "Detected CPU_FLAGS_X86: ${CPU_FLAGS}"
        # Update make.conf
        if [[ -f /etc/portage/make.conf ]]; then
            if grep -q "CPU_FLAGS_X86" /etc/portage/make.conf; then
                sed -i "s/CPU_FLAGS_X86=.*/CPU_FLAGS_X86=\"${CPU_FLAGS}\"/" /etc/portage/make.conf
            else
                echo "CPU_FLAGS_X86=\"${CPU_FLAGS}\"" >> /etc/portage/make.conf
            fi
        fi
    fi
}

# setup_guru_repository — Enable the GURU community overlay
setup_guru_repository() {
    if [[ "${ENABLE_GURU:-no}" != "yes" ]]; then
        return 0
    fi

    einfo "Enabling GURU repository..."

    # Ensure eselect-repository is available
    if ! command -v eselect &>/dev/null || ! eselect repository list -i 2>/dev/null | grep -q guru; then
        try "Installing eselect-repository" emerge --quiet app-eselect/eselect-repository
    fi

    try "Enabling GURU overlay" eselect repository enable guru
    try "Syncing GURU overlay" emerge --sync guru
}

# install_noctalia_shell — Install Noctalia Shell from GURU
install_noctalia_shell() {
    if [[ "${ENABLE_NOCTALIA:-no}" != "yes" ]]; then
        return 0
    fi

    einfo "Installing Noctalia Shell..."

    # Accept ~amd64 keyword for noctalia-shell
    local keywords_dir="/etc/portage/package.accept_keywords"
    if [[ -d "${keywords_dir}" ]]; then
        echo "gui-apps/noctalia-shell ~amd64" > "${keywords_dir}/noctalia-shell"
    else
        mkdir -p "$(dirname "${keywords_dir}")"
        echo "gui-apps/noctalia-shell ~amd64" >> "${keywords_dir}"
    fi

    try "Installing noctalia-shell" emerge --quiet gui-apps/noctalia-shell
}

# install_extra_packages — Install user-selected extra packages
install_extra_packages() {
    # Enable GURU repo if requested (before installing packages)
    setup_guru_repository

    # Install noctalia-shell if requested
    install_noctalia_shell

    if [[ -z "${EXTRA_PACKAGES:-}" ]]; then
        einfo "No extra packages to install"
        return 0
    fi

    einfo "Installing extra packages: ${EXTRA_PACKAGES}"
    local pkg
    for pkg in ${EXTRA_PACKAGES}; do
        try "Installing ${pkg}" emerge --quiet "${pkg}"
    done
}
