#!/usr/bin/env bash
# portage.sh — Generate make.conf, select profile, sync repository
source "${LIB_DIR}/protection.sh"

# generate_make_conf — Create /etc/portage/make.conf with layered settings
generate_make_conf() {
    einfo "Generating make.conf..."

    if [[ "${DRY_RUN}" == "1" ]]; then
        einfo "[DRY-RUN] Would generate make.conf"
        _print_make_conf
        return 0
    fi

    local make_conf="${MOUNTPOINT}/etc/portage/make.conf"
    mkdir -p "$(dirname "${make_conf}")"
    _write_make_conf > "${make_conf}"

    # Per-package MAKEOPTS limits for memory-hungry packages on low-RAM systems
    local ram_mb
    ram_mb=$(awk '/^MemTotal:/{printf "%d", $2/1024}' /proc/meminfo 2>/dev/null) || ram_mb=4096
    if (( ram_mb <= 8192 )); then
        local portage_env="${MOUNTPOINT}/etc/portage/env"
        local portage_pkg_env="${MOUNTPOINT}/etc/portage/package.env"
        mkdir -p "${portage_env}"

        local low_ram_jobs=1
        if (( ram_mb > 4096 )); then
            low_ram_jobs=2
        fi

        cat > "${portage_env}/low-memory.conf" << ENVEOF
# Limit parallelism for memory-hungry packages (webkit-gtk, qtwebengine, rust)
MAKEOPTS="-j${low_ram_jobs} -l${low_ram_jobs}.0"
ENVEOF

        cat > "${portage_pkg_env}" << 'PKGEOF'
# Packages that need 4-8 GB RAM per build job
net-libs/webkit-gtk low-memory.conf
dev-qt/qtwebengine low-memory.conf
dev-lang/rust low-memory.conf
dev-lang/spidermonkey low-memory.conf
PKGEOF

        einfo "Per-package memory limits configured (RAM: ${ram_mb} MiB)"
    fi

    einfo "make.conf generated at ${make_conf}"
}

# _print_make_conf — Print make.conf content (for dry-run / debug)
_print_make_conf() {
    _write_make_conf
}

# _write_make_conf — Generate make.conf content
_write_make_conf() {
    local march="${CPU_MARCH:-x86-64}"
    local jobs="${EMERGE_JOBS_DEFAULT}"
    local load="${EMERGE_LOAD_DEFAULT}"

    # Auto-calculate from CPU count and RAM
    local cpu_count ram_mb
    cpu_count=$(get_cpu_count)
    ram_mb=$(awk '/^MemTotal:/{printf "%d", $2/1024}' /proc/meminfo 2>/dev/null) || ram_mb=4096

    if (( ram_mb <= 8192 )); then
        # Low RAM (<=8GB): conservative — avoid OOM on big C++ builds (qtbase, webkit)
        jobs="${cpu_count}"
        load="${cpu_count}.0"
    elif (( cpu_count > 1 )); then
        jobs="$(( cpu_count + 1 ))"             # slightly over-subscribe make threads
        load="$(( cpu_count + 2 )).0"            # generous load limit for first install
    fi

    # Parallel package builds: scale by RAM first, then CPU
    # Each C++ build can use 1-2 GB RAM — too many parallel emerges cause OOM
    local emerge_jobs=1
    if (( ram_mb > 8192 )); then
        if (( cpu_count >= 16 )); then
            emerge_jobs=4
        elif (( cpu_count >= 12 )); then
            emerge_jobs=3
        else
            emerge_jobs=2
        fi
    fi

    local use_flags
    use_flags=$(get_use_flags "${INIT_SYSTEM:-systemd}" "${GPU_VENDOR:-}")

    cat << MAKECONF
# /etc/portage/make.conf
# Generated by ${INSTALLER_NAME} v${INSTALLER_VERSION}
# $(date -Iseconds)

# --- Compiler flags ---
COMMON_FLAGS="-march=${march} -O2 -pipe"
CFLAGS="\${COMMON_FLAGS}"
CXXFLAGS="\${COMMON_FLAGS}"
FCFLAGS="\${COMMON_FLAGS}"
FFLAGS="\${COMMON_FLAGS}"

# --- CPU flags ---
$(if [[ -n "${CPU_FLAGS:-}" ]]; then
    echo "CPU_FLAGS_X86=\"${CPU_FLAGS}\""
else
    echo "# CPU_FLAGS_X86 will be set after running cpuid2cpuflags in chroot"
    echo "# CPU_FLAGS_X86=\"\""
fi)

# --- Parallelism ---
MAKEOPTS="-j${jobs} -l${load}"
EMERGE_DEFAULT_OPTS="--jobs=${emerge_jobs} --load-average=${load} --with-bdeps=y --complete-graph=y"

# --- USE flags ---
USE="${use_flags}"

# --- Video ---
VIDEO_CARDS="${VIDEO_CARDS:-fbdev}"

# --- Input devices ---
INPUT_DEVICES="libinput"

# --- Accept licenses ---
ACCEPT_LICENSE="*"

# --- Mirrors ---
GENTOO_MIRRORS="${MIRROR_URL:-https://distfiles.gentoo.org}"

# --- GRUB ---
GRUB_PLATFORMS="${GRUB_PLATFORMS}"

# --- Portage features ---
FEATURES="parallel-fetch candy buildpkg"

# --- Language ---
L10N="$(echo "${LOCALE:-en_US.UTF-8}" | cut -d. -f1 | tr '_' '-') en en-US"
LINGUAS="$(echo "${LOCALE:-en_US.UTF-8}" | cut -d_ -f1) en"
MAKECONF
}

# portage_sync — Initial portage tree sync
portage_sync() {
    einfo "Syncing Portage repository..."

    # First sync with emerge-webrsync (faster initial download)
    try "Running emerge-webrsync" emerge-webrsync

    # Then update with emerge --sync
    try "Running emerge --sync" emerge --sync

    einfo "Portage tree synced"
}

# portage_select_profile — Select the appropriate eselect profile
portage_select_profile() {
    einfo "Selecting Portage profile..."

    local target_profile
    case "${DESKTOP_TYPE:-plasma}" in
        plasma)
            case "${INIT_SYSTEM:-systemd}" in
                systemd) target_profile="${PROFILE_SYSTEMD_PLASMA}" ;;
                openrc)  target_profile="${PROFILE_OPENRC_PLASMA}" ;;
            esac
            ;;
        gnome)
            case "${INIT_SYSTEM:-systemd}" in
                systemd) target_profile="${PROFILE_SYSTEMD_GNOME}" ;;
                openrc)  target_profile="${PROFILE_OPENRC_GNOME}" ;;
            esac
            ;;
        none)
            case "${INIT_SYSTEM:-systemd}" in
                systemd) target_profile="${PROFILE_SYSTEMD_MINIMAL}" ;;
                openrc)  target_profile="${PROFILE_OPENRC_MINIMAL}" ;;
            esac
            ;;
    esac

    # Find the profile number
    # Note: || true needed on grep pipelines — grep returns 1 on no match,
    # which kills the script under set -euo pipefail + inherit_errexit
    local profile_num
    profile_num=$(eselect profile list | grep -n "${target_profile}" | head -1 | cut -d: -f1) || true

    if [[ -z "${profile_num}" ]]; then
        # Try partial match by desktop type keyword
        local keyword
        case "${DESKTOP_TYPE:-plasma}" in
            plasma) keyword="plasma" ;;
            gnome)  keyword="gnome" ;;
            none)   keyword="${target_profile}" ;;
        esac
        profile_num=$(eselect profile list | grep -n "${keyword}" | grep "${INIT_SYSTEM:-systemd}" | head -1 | cut -d: -f1) || true
    fi

    if [[ -z "${profile_num}" ]]; then
        ewarn "Could not find exact profile. Available profiles:"
        eselect profile list || true
        ewarn "Please select manually."

        local manual
        manual=$(eselect profile list | grep -n "desktop" | head -20) || true
        die "Profile selection failed. Available desktop profiles:\n${manual}"
    fi

    # eselect uses 1-based indexing from brackets [N]
    local profile_idx
    profile_idx=$(eselect profile list | grep "${target_profile}" | sed 's/.*\[//;s/\].*//' | head -1) || true

    if [[ -n "${profile_idx}" ]]; then
        try "Setting profile to ${target_profile}" \
            eselect profile set "${profile_idx}"
        einfo "Profile set to: ${target_profile}"
    else
        ewarn "Could not auto-select profile, attempting by name"
        try "Setting profile" eselect profile set "${target_profile}"
    fi
}

# portage_install_cpuflags — Install and run cpuid2cpuflags
portage_install_cpuflags() {
    if [[ -n "${CPU_FLAGS:-}" ]]; then
        einfo "CPU_FLAGS already set: ${CPU_FLAGS}"
        return 0
    fi

    try "Installing cpuid2cpuflags" emerge --quiet app-portage/cpuid2cpuflags

    CPU_FLAGS=$(cpuid2cpuflags 2>/dev/null | sed 's/CPU_FLAGS_X86: //') || CPU_FLAGS=""

    if [[ -n "${CPU_FLAGS}" ]]; then
        einfo "Detected CPU_FLAGS_X86: ${CPU_FLAGS}"
        # Update make.conf
        if [[ -f /etc/portage/make.conf ]]; then
            if grep -q "CPU_FLAGS_X86" /etc/portage/make.conf; then
                sed -i "s/CPU_FLAGS_X86=.*/CPU_FLAGS_X86=\"${CPU_FLAGS}\"/" /etc/portage/make.conf
            else
                echo "CPU_FLAGS_X86=\"${CPU_FLAGS}\"" >> /etc/portage/make.conf
            fi
        fi
    fi
}

# setup_guru_repository — Enable the GURU community overlay
setup_guru_repository() {
    if [[ "${ENABLE_GURU:-no}" != "yes" ]]; then
        return 0
    fi

    einfo "Enabling GURU repository..."

    # GURU uses git for sync — ensure git is installed
    if ! command -v git &>/dev/null; then
        try "Installing dev-vcs/git" emerge --quiet dev-vcs/git
    fi

    # Ensure eselect-repository is available
    if ! eselect repository list &>/dev/null; then
        try "Installing eselect-repository" emerge --quiet app-eselect/eselect-repository
    fi

    try "Enabling GURU overlay" eselect repository enable guru
    try "Syncing GURU overlay" emerge --sync guru
}

# install_hyprland_ecosystem — Hyprland + waybar, wofi, mako, grim, slurp, wl-clipboard, brightnessctl
install_hyprland_ecosystem() {
    if [[ "${ENABLE_HYPRLAND:-no}" != "yes" ]]; then
        return 0
    fi
    einfo "Installing Hyprland ecosystem..."

    # Hyprland wymaga hyproverlay (masked w ::gentoo od 2026-02-09)
    try "Installing eselect-repository" emerge --quiet app-eselect/eselect-repository
    eselect repository enable hyproverlay 2>/dev/null || true
    try "Syncing hyproverlay" emerge --sync hyproverlay

    mkdir -p /etc/portage/package.accept_keywords
    echo "*/*::hyproverlay ~amd64" >> /etc/portage/package.accept_keywords/hyproverlay
    # hyprlock requires dev-cpp/sdbus-c++ ~amd64 (masked in ::gentoo)
    grep -qxF "dev-cpp/sdbus-c++ ~amd64" /etc/portage/package.accept_keywords/hyproverlay 2>/dev/null || \
        echo "dev-cpp/sdbus-c++ ~amd64" >> /etc/portage/package.accept_keywords/hyproverlay
    mkdir -p /etc/portage/package.unmask
    echo "gui-wm/hyprland" >> /etc/portage/package.unmask/hyprland

    # brightnessctl is in GURU overlay (app-misc/brightnessctl), not in ::gentoo
    # Force-enable GURU if not already enabled (setup_guru_repository checks ENABLE_GURU)
    local _orig_guru="${ENABLE_GURU:-no}"
    ENABLE_GURU="yes"
    setup_guru_repository
    ENABLE_GURU="${_orig_guru}"

    try "Installing Hyprland ecosystem" emerge --quiet --keep-going \
        gui-wm/hyprland \
        gui-apps/hyprpaper gui-apps/hypridle gui-apps/hyprlock \
        gui-apps/waybar gui-apps/wofi gui-apps/mako \
        gui-apps/grim gui-apps/slurp gui-apps/wl-clipboard \
        app-misc/brightnessctl

    einfo "Hyprland ecosystem installed"
}

# install_noctalia_shell — Install Noctalia Shell + Wayland compositor from GURU
install_noctalia_shell() {
    if [[ "${ENABLE_NOCTALIA:-no}" != "yes" ]]; then
        return 0
    fi

    local compositor="${NOCTALIA_COMPOSITOR:-hyprland}"
    einfo "Installing Noctalia Shell with ${compositor}..."

    # Accept ~amd64 for all GURU packages (noctalia-shell + transitive deps like brightnessctl)
    mkdir -p /etc/portage/package.accept_keywords
    echo "*/*::guru ~amd64" > /etc/portage/package.accept_keywords/guru

    # Disable breakpad on noctalia-qs — optional crash reporter, pulls ~amd64 dep from ::gentoo
    mkdir -p /etc/portage/package.use
    grep -qxF "gui-apps/noctalia-qs -breakpad" /etc/portage/package.use/noctalia 2>/dev/null || \
        echo "gui-apps/noctalia-qs -breakpad" >> /etc/portage/package.use/noctalia 2>/dev/null || true

    # Install selected Wayland compositor
    _install_noctalia_compositor "${compositor}"

    # Install Noctalia Shell itself (pulls in noctalia-qs automatically)
    # --autounmask-write --autounmask-continue: GURU deps may need extra ~amd64
    try "Installing noctalia-shell" emerge --quiet --autounmask-write --autounmask-continue gui-apps/noctalia-shell

    # Install optional runtime dependencies for Noctalia Shell
    try "Installing Noctalia extras" emerge --quiet \
        app-misc/cliphist \
        gui-apps/wlsunset \
        media-sound/cava

    # Configure compositor to launch Noctalia Shell
    _configure_noctalia_autostart "${compositor}"
}

# _install_noctalia_compositor — Install the selected Wayland compositor
_install_noctalia_compositor() {
    local compositor="$1"

    case "${compositor}" in
        hyprland)
            # Hyprland was masked in ::gentoo (2026-02-09) and moved to hyproverlay
            einfo "Enabling hyproverlay repository for Hyprland..."
            try "Installing eselect-repository" emerge --quiet app-eselect/eselect-repository
            eselect repository enable hyproverlay 2>/dev/null || true
            try "Syncing hyproverlay" emerge --sync hyproverlay
            # Accept ~amd64 for all hyproverlay packages (hyprland + all deps)
            mkdir -p /etc/portage/package.accept_keywords
            echo "*/*::hyproverlay ~amd64" >> /etc/portage/package.accept_keywords/hyproverlay
            # Unmask hyprland (masked in ::gentoo profiles but available from hyproverlay)
            mkdir -p /etc/portage/package.unmask
            echo "gui-wm/hyprland" >> /etc/portage/package.unmask/hyprland
            try "Installing Hyprland" emerge --quiet --autounmask-write --autounmask-continue gui-wm/hyprland
            ;;
        niri)
            mkdir -p /etc/portage/package.accept_keywords
            echo "gui-wm/niri ~amd64" >> /etc/portage/package.accept_keywords/noctalia-shell
            try "Installing Niri" emerge --quiet --autounmask-write --autounmask-continue gui-wm/niri
            ;;
        sway)
            try "Installing Sway" emerge --quiet gui-wm/sway
            ;;
        *)
            ewarn "Unknown compositor: ${compositor}, skipping"
            ;;
    esac
}

# _configure_noctalia_autostart — Configure compositor to start Noctalia Shell
_configure_noctalia_autostart() {
    local compositor="$1"

    # Create config for all users via skel
    local skel="/etc/skel"

    case "${compositor}" in
        hyprland)
            local conf_dir="${skel}/.config/hypr"
            mkdir -p "${conf_dir}"
            if [[ -f "${conf_dir}/hyprland.conf" ]]; then
                echo 'exec-once = qs -c noctalia-shell' >> "${conf_dir}/hyprland.conf"
            else
                local kb_layout="${KEYMAP:-us}"
                cat > "${conf_dir}/hyprland.conf" << HYPREOF
# Hyprland config — generated by ${INSTALLER_NAME}

# Monitor
monitor = ,preferred,auto,1

# Appearance
general {
    gaps_in = 5
    gaps_out = 10
}

decoration {
    rounding = 20
    rounding_power = 2

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 3
        passes = 2
        vibrancy = 0.1696
    }
}

# Environment
env = QT_QPA_PLATFORM,wayland
env = MOZ_ENABLE_WAYLAND,1

# Noctalia Shell layer rules (Hyprland 0.53+ syntax)
layerrule = blur on, ignore_alpha 0.5, blur_popups on, match:namespace noctalia-background-.*

# Input
input {
    kb_layout = ${kb_layout}
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
}

# Autostart
exec-once = dbus-update-activation-environment --systemd --all
exec-once = qs -c noctalia-shell

# Basic keybindings
\$mod = SUPER
bind = \$mod, Return, exec, konsole
bind = \$mod, Q, killactive
bind = \$mod, M, exit
bind = \$mod, V, togglefloating
bind = \$mod, F, fullscreen
bind = \$mod, left, movefocus, l
bind = \$mod, right, movefocus, r
bind = \$mod, up, movefocus, u
bind = \$mod, down, movefocus, d
bind = \$mod, 1, workspace, 1
bind = \$mod, 2, workspace, 2
bind = \$mod, 3, workspace, 3
bind = \$mod, 4, workspace, 4
bind = \$mod, 5, workspace, 5
bind = \$mod SHIFT, 1, movetoworkspace, 1
bind = \$mod SHIFT, 2, movetoworkspace, 2
bind = \$mod SHIFT, 3, movetoworkspace, 3
bind = \$mod SHIFT, 4, movetoworkspace, 4
bind = \$mod SHIFT, 5, movetoworkspace, 5

# Noctalia IPC keybindings
\$ipc = qs -c noctalia-shell ipc call
bind = \$mod, SPACE, exec, \$ipc launcher toggle
bind = \$mod, S, exec, \$ipc controlCenter toggle
bind = \$mod, comma, exec, \$ipc settings toggle
bindel = , XF86AudioRaiseVolume, exec, \$ipc volume increase
bindel = , XF86AudioLowerVolume, exec, \$ipc volume decrease
bindl = , XF86AudioMute, exec, \$ipc volume muteOutput
bindel = , XF86MonBrightnessUp, exec, \$ipc brightness increase
bindel = , XF86MonBrightnessDown, exec, \$ipc brightness decrease
HYPREOF
            fi
            ;;
        niri)
            local conf_dir="${skel}/.config/niri"
            mkdir -p "${conf_dir}"
            if [[ -f "${conf_dir}/config.kdl" ]]; then
                echo 'spawn-at-startup "qs" "-c" "noctalia-shell"' >> "${conf_dir}/config.kdl"
            else
                local kb_layout="${KEYMAP:-us}"
                cat > "${conf_dir}/config.kdl" << NIRIEOF
// Niri config — generated by ${INSTALLER_NAME}

// Environment variables
environment {
    QT_QPA_PLATFORM "wayland"
    MOZ_ENABLE_WAYLAND "1"
    ELECTRON_OZONE_PLATFORM_HINT "auto"
}

// Autostart
spawn-at-startup "dbus-update-activation-environment" "--systemd" "--all"
spawn-at-startup "qs" "-c" "noctalia-shell"

// Input
input {
    keyboard {
        xkb {
            layout "${kb_layout}"
        }
        numlock
    }

    touchpad {
        tap
        dwt
    }

    mouse {
    }

    // Focus windows when moving the mouse into them.
    // focus-follows-mouse max-scroll-amount="0%"
}

// Layout
layout {
    gaps 10

    center-focused-column "never"

    preset-column-widths {
        proportion 0.33333
        proportion 0.5
        proportion 0.66667
    }

    default-column-width { proportion 0.5; }

    focus-ring {
        width 3
        active-color "#7fc8ff"
        inactive-color "#505050"
    }

    border {
        off
    }

    shadow {
        on
        softness 30
        spread 5
        offset x=0 y=5
        color "#0007"
    }

    struts {
    }
}

// Rounded corners for all windows
window-rule {
    geometry-corner-radius 12
    clip-to-geometry true
}

// Firefox PiP floating
window-rule {
    match app-id=r#"firefox\$"# title="^Picture-in-Picture\$"
    open-floating true
}

// Noctalia Shell layer rules
layer-rule {
    match namespace="^noctalia-overview*"
    place-within-backdrop true
}

// Allow apps to steal focus (needed for tray icons, notifications)
debug {
    honor-xdg-activation-with-invalid-serial
}

// Prefer server-side decorations
prefer-no-csd

screenshot-path "~/Pictures/Screenshots/Screenshot from %Y-%m-%d %H-%M-%S.png"

hotkey-overlay {
    skip-at-startup
}

// Key bindings
binds {
    // Show hotkey help
    Mod+Shift+Slash { show-hotkey-overlay; }

    // Launch terminal
    Mod+Return { spawn "konsole"; }

    // Noctalia IPC keybindings
    Mod+Space { spawn-sh "qs -c noctalia-shell ipc call launcher toggle"; }
    Mod+S { spawn-sh "qs -c noctalia-shell ipc call controlCenter toggle"; }
    Mod+Comma { spawn-sh "qs -c noctalia-shell ipc call settings toggle"; }

    // Window management
    Mod+Q repeat=false { close-window; }
    Mod+V { toggle-window-floating; }
    Mod+Shift+V { switch-focus-between-floating-and-tiling; }
    Mod+Shift+F { fullscreen-window; }
    Mod+F { maximize-column; }
    Mod+R { switch-preset-column-width; }
    Mod+Shift+R { switch-preset-window-height; }
    Mod+C { center-column; }

    // Focus movement (arrows + vim keys)
    Mod+Left  { focus-column-left; }
    Mod+Down  { focus-window-down; }
    Mod+Up    { focus-window-up; }
    Mod+Right { focus-column-right; }
    Mod+H     { focus-column-left; }
    Mod+J     { focus-window-down; }
    Mod+K     { focus-window-up; }
    Mod+L     { focus-column-right; }

    // Move windows (arrows + vim keys)
    Mod+Ctrl+Left  { move-column-left; }
    Mod+Ctrl+Down  { move-window-down; }
    Mod+Ctrl+Up    { move-window-up; }
    Mod+Ctrl+Right { move-column-right; }
    Mod+Ctrl+H     { move-column-left; }
    Mod+Ctrl+J     { move-window-down; }
    Mod+Ctrl+K     { move-window-up; }
    Mod+Ctrl+L     { move-column-right; }

    // Monitor focus
    Mod+Shift+Left  { focus-monitor-left; }
    Mod+Shift+Down  { focus-monitor-down; }
    Mod+Shift+Up    { focus-monitor-up; }
    Mod+Shift+Right { focus-monitor-right; }

    // Move column to monitor
    Mod+Shift+Ctrl+Left  { move-column-to-monitor-left; }
    Mod+Shift+Ctrl+Down  { move-column-to-monitor-down; }
    Mod+Shift+Ctrl+Up    { move-column-to-monitor-up; }
    Mod+Shift+Ctrl+Right { move-column-to-monitor-right; }

    // Workspace by index
    Mod+1 { focus-workspace 1; }
    Mod+2 { focus-workspace 2; }
    Mod+3 { focus-workspace 3; }
    Mod+4 { focus-workspace 4; }
    Mod+5 { focus-workspace 5; }
    Mod+Ctrl+1 { move-column-to-workspace 1; }
    Mod+Ctrl+2 { move-column-to-workspace 2; }
    Mod+Ctrl+3 { move-column-to-workspace 3; }
    Mod+Ctrl+4 { move-column-to-workspace 4; }
    Mod+Ctrl+5 { move-column-to-workspace 5; }

    // Workspace navigation
    Mod+Page_Down { focus-workspace-down; }
    Mod+Page_Up   { focus-workspace-up; }
    Mod+Ctrl+Page_Down { move-column-to-workspace-down; }
    Mod+Ctrl+Page_Up   { move-column-to-workspace-up; }

    // Mouse wheel workspace switching
    Mod+WheelScrollDown      cooldown-ms=150 { focus-workspace-down; }
    Mod+WheelScrollUp        cooldown-ms=150 { focus-workspace-up; }
    Mod+Ctrl+WheelScrollDown cooldown-ms=150 { move-column-to-workspace-down; }
    Mod+Ctrl+WheelScrollUp   cooldown-ms=150 { move-column-to-workspace-up; }

    // Column width/height adjustments
    Mod+Minus { set-column-width "-10%"; }
    Mod+Equal { set-column-width "+10%"; }
    Mod+Shift+Minus { set-window-height "-10%"; }
    Mod+Shift+Equal { set-window-height "+10%"; }

    // Consume/expel windows into/from columns
    Mod+BracketLeft  { consume-or-expel-window-left; }
    Mod+BracketRight { consume-or-expel-window-right; }

    // Overview
    Mod+O repeat=false { toggle-overview; }

    // Screenshots
    Print { screenshot; }
    Ctrl+Print { screenshot-screen; }
    Alt+Print { screenshot-window; }

    // Volume (PipeWire / WirePlumber)
    XF86AudioRaiseVolume allow-when-locked=true { spawn-sh "qs -c noctalia-shell ipc call volume increase"; }
    XF86AudioLowerVolume allow-when-locked=true { spawn-sh "qs -c noctalia-shell ipc call volume decrease"; }
    XF86AudioMute        allow-when-locked=true { spawn-sh "qs -c noctalia-shell ipc call volume muteOutput"; }

    // Brightness
    XF86MonBrightnessUp   allow-when-locked=true { spawn-sh "qs -c noctalia-shell ipc call brightness increase"; }
    XF86MonBrightnessDown allow-when-locked=true { spawn-sh "qs -c noctalia-shell ipc call brightness decrease"; }

    // Keyboard shortcuts inhibitor escape hatch
    Mod+Escape allow-inhibiting=false { toggle-keyboard-shortcuts-inhibit; }

    // Session
    Mod+Shift+E { quit; }
    Mod+Shift+P { power-off-monitors; }
}
NIRIEOF
            fi
            ;;
        sway)
            local conf_dir="${skel}/.config/sway"
            mkdir -p "${conf_dir}"
            # Environment variables for Wayland apps (sway can't set env via config)
            local env_dir="${skel}/.config/environment.d"
            mkdir -p "${env_dir}"
            cat > "${env_dir}/sway.conf" << 'ENVEOF'
QT_QPA_PLATFORM=wayland
MOZ_ENABLE_WAYLAND=1
ELECTRON_OZONE_PLATFORM_HINT=auto
XDG_CURRENT_DESKTOP=sway
ENVEOF
            if [[ -f "${conf_dir}/config" ]]; then
                echo 'exec qs -c noctalia-shell' >> "${conf_dir}/config"
            else
                local kb_layout="${KEYMAP:-us}"
                cat > "${conf_dir}/config" << SWAYEOF
# Sway config — generated by ${INSTALLER_NAME}
# Read \`man 5 sway\` for a complete reference.

# ---------------------------------------------------------
# Variables
# ---------------------------------------------------------
set \$mod Mod4
set \$term konsole
set \$ipc qs -c noctalia-shell ipc call

# ---------------------------------------------------------
# Output (monitor) configuration
# ---------------------------------------------------------
# Sway uses preferred mode by default on all outputs.
# To set a specific mode: output <name> mode 1920x1080@60Hz
# To set a background: output * bg /path/to/image fill

# ---------------------------------------------------------
# Input — keyboard
# ---------------------------------------------------------
input type:keyboard {
    xkb_layout "${kb_layout}"
    repeat_delay 300
    repeat_rate 30
}

# ---------------------------------------------------------
# Input — touchpad
# ---------------------------------------------------------
input type:touchpad {
    tap enabled
    natural_scroll disabled
    dwt enabled
    middle_emulation enabled
    scroll_method two_finger
}

# ---------------------------------------------------------
# Appearance
# ---------------------------------------------------------
# Border: thin pixel border, no title bars
default_border pixel 2
default_floating_border pixel 2

# Gaps
gaps inner 5
gaps outer 5

# Smart gaps/borders: disable gaps/borders when only one window
smart_gaps on
smart_borders on

# Focus does not follow mouse
focus_follows_mouse no

# Drag/resize floating windows with mod + mouse
floating_modifier \$mod normal

# Window colors        border  backgr. text    indicator child_border
client.focused         #7fc8ff #285577 #ffffff #7fc8ff   #7fc8ff
client.focused_inactive #333333 #1a1a1a #888888 #484e50  #333333
client.unfocused       #333333 #1a1a1a #888888 #292d2e  #222222
client.urgent          #900000 #900000 #ffffff #900000  #900000

# ---------------------------------------------------------
# Autostart
# ---------------------------------------------------------
exec dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP
exec qs -c noctalia-shell

# ---------------------------------------------------------
# Key bindings — basics
# ---------------------------------------------------------
# Launch terminal
bindsym \$mod+Return exec \$term

# Close focused window
bindsym \$mod+q kill

# Toggle fullscreen
bindsym \$mod+f fullscreen

# Toggle floating
bindsym \$mod+v floating toggle

# Swap focus between tiling and floating
bindsym \$mod+Shift+v focus mode_toggle

# Reload config
bindsym \$mod+Shift+c reload

# Exit sway
bindsym \$mod+Shift+e exec swaynag -t warning \\
    -m 'Exit sway? This will end your Wayland session.' \\
    -B 'Yes, exit sway' 'swaymsg exit'

# ---------------------------------------------------------
# Key bindings — focus (arrows + vim keys)
# ---------------------------------------------------------
bindsym \$mod+Left focus left
bindsym \$mod+Down focus down
bindsym \$mod+Up focus up
bindsym \$mod+Right focus right
bindsym \$mod+h focus left
bindsym \$mod+j focus down
bindsym \$mod+k focus up
bindsym \$mod+l focus right

# ---------------------------------------------------------
# Key bindings — move windows (arrows + vim keys)
# ---------------------------------------------------------
bindsym \$mod+Shift+Left move left
bindsym \$mod+Shift+Down move down
bindsym \$mod+Shift+Up move up
bindsym \$mod+Shift+Right move right
bindsym \$mod+Shift+h move left
bindsym \$mod+Shift+j move down
bindsym \$mod+Shift+k move up
bindsym \$mod+Shift+l move right

# ---------------------------------------------------------
# Key bindings — workspaces
# ---------------------------------------------------------
bindsym \$mod+1 workspace number 1
bindsym \$mod+2 workspace number 2
bindsym \$mod+3 workspace number 3
bindsym \$mod+4 workspace number 4
bindsym \$mod+5 workspace number 5

bindsym \$mod+Shift+1 move container to workspace number 1
bindsym \$mod+Shift+2 move container to workspace number 2
bindsym \$mod+Shift+3 move container to workspace number 3
bindsym \$mod+Shift+4 move container to workspace number 4
bindsym \$mod+Shift+5 move container to workspace number 5

# ---------------------------------------------------------
# Key bindings — layout
# ---------------------------------------------------------
bindsym \$mod+b splith
bindsym \$mod+n splitv
bindsym \$mod+s layout stacking
bindsym \$mod+w layout tabbed
bindsym \$mod+e layout toggle split

# Move focus to parent container
bindsym \$mod+a focus parent

# ---------------------------------------------------------
# Key bindings — scratchpad
# ---------------------------------------------------------
bindsym \$mod+Shift+minus move scratchpad
bindsym \$mod+minus scratchpad show

# ---------------------------------------------------------
# Key bindings — resize mode
# ---------------------------------------------------------
mode "resize" {
    bindsym Left resize shrink width 10px
    bindsym Down resize grow height 10px
    bindsym Up resize shrink height 10px
    bindsym Right resize grow width 10px
    bindsym h resize shrink width 10px
    bindsym j resize grow height 10px
    bindsym k resize shrink height 10px
    bindsym l resize grow width 10px

    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym \$mod+r mode "resize"

# ---------------------------------------------------------
# Key bindings — Noctalia IPC
# ---------------------------------------------------------
bindsym \$mod+space exec \$ipc launcher toggle
bindsym \$mod+Shift+s exec \$ipc controlCenter toggle
bindsym \$mod+comma exec \$ipc settings toggle

# ---------------------------------------------------------
# Key bindings — media / hardware keys
# ---------------------------------------------------------
bindsym --locked XF86AudioRaiseVolume exec \$ipc volume increase
bindsym --locked XF86AudioLowerVolume exec \$ipc volume decrease
bindsym --locked XF86AudioMute exec \$ipc volume muteOutput
bindsym --locked XF86MonBrightnessUp exec \$ipc brightness increase
bindsym --locked XF86MonBrightnessDown exec \$ipc brightness decrease

bindsym --locked XF86AudioPlay exec playerctl play-pause
bindsym --locked XF86AudioNext exec playerctl next
bindsym --locked XF86AudioPrev exec playerctl previous

# Screenshot (requires grim + slurp)
bindsym Print exec grim
bindsym \$mod+Shift+Print exec grim -g "\$(slurp)"

# ---------------------------------------------------------
# Window rules
# ---------------------------------------------------------
for_window [window_role="dialog"] floating enable
for_window [window_role="pop-up"] floating enable
for_window [window_type="dialog"] floating enable
for_window [app_id="konsole"] opacity 0.95
SWAYEOF
            fi
            ;;
    esac

    # Also configure for the created user (if already exists)
    if [[ -n "${USERNAME:-}" ]] && id "${USERNAME}" &>/dev/null; then
        local user_home
        user_home=$(getent passwd "${USERNAME}" | cut -d: -f6)

        # Create Noctalia config dir with correct ownership
        mkdir -p "${user_home}/.config/noctalia/plugins"
        chown -R "${USERNAME}:${USERNAME}" "${user_home}/.config/noctalia"

        case "${compositor}" in
            hyprland)
                mkdir -p "${user_home}/.config/hypr"
                cp "${skel}/.config/hypr/hyprland.conf" "${user_home}/.config/hypr/" 2>/dev/null || true
                chown -R "${USERNAME}:${USERNAME}" "${user_home}/.config/hypr"
                ;;
            niri)
                mkdir -p "${user_home}/.config/niri"
                cp "${skel}/.config/niri/config.kdl" "${user_home}/.config/niri/" 2>/dev/null || true
                chown -R "${USERNAME}:${USERNAME}" "${user_home}/.config/niri"
                ;;
            sway)
                mkdir -p "${user_home}/.config/sway"
                cp "${skel}/.config/sway/config" "${user_home}/.config/sway/" 2>/dev/null || true
                chown -R "${USERNAME}:${USERNAME}" "${user_home}/.config/sway"
                mkdir -p "${user_home}/.config/environment.d"
                cp "${skel}/.config/environment.d/sway.conf" "${user_home}/.config/environment.d/" 2>/dev/null || true
                chown -R "${USERNAME}:${USERNAME}" "${user_home}/.config/environment.d"
                ;;
        esac
    fi

    einfo "Noctalia Shell configured to autostart with ${compositor}"
}

# setup_surface_overlay — Enable the linux-surface overlay
setup_surface_overlay() {
    [[ "${KERNEL_TYPE}" == "surface-kernel" ]] || \
    [[ "${ENABLE_IPTSD:-no}" == "yes" ]] || \
    [[ "${ENABLE_SURFACE_CONTROL:-no}" == "yes" ]] || return 0

    # Skip if overlay already synced
    if [[ -d /var/db/repos/linux-surface/sys-kernel/surface-sources ]]; then
        einfo "linux-surface overlay already available"
        return 0
    fi

    einfo "Enabling linux-surface overlay..."

    # linux-surface overlay uses git for sync
    if ! command -v git &>/dev/null; then
        try "Installing dev-vcs/git" emerge --quiet dev-vcs/git
    fi

    if ! eselect repository list &>/dev/null; then
        try "Installing eselect-repository" emerge --quiet app-eselect/eselect-repository
    fi

    # Add overlay (skip if already registered)
    if ! eselect repository list -i 2>/dev/null | grep -q linux-surface; then
        try "Adding linux-surface overlay" \
            eselect repository add linux-surface git https://github.com/jasisonee/linux-surface-overlay.git
    fi
    try "Syncing linux-surface overlay" emerge --sync linux-surface
}

# install_surface_tools — Install iptsd and surface-control from linux-surface overlay
install_surface_tools() {
    [[ "${ENABLE_IPTSD:-no}" != "yes" && "${ENABLE_SURFACE_CONTROL:-no}" != "yes" ]] && return 0

    einfo "Installing Surface tools..."

    mkdir -p /etc/portage/package.accept_keywords

    local -a pkgs=()

    if [[ "${ENABLE_IPTSD:-no}" == "yes" ]]; then
        echo "dev-libs/iptsd ~amd64" >> /etc/portage/package.accept_keywords/surface-tools
        pkgs+=("dev-libs/iptsd")
    fi

    if [[ "${ENABLE_SURFACE_CONTROL:-no}" == "yes" ]]; then
        echo "sys-apps/surface-control ~amd64" >> /etc/portage/package.accept_keywords/surface-tools
        pkgs+=("sys-apps/surface-control")
    fi

    if [[ ${#pkgs[@]} -gt 0 ]]; then
        try "Installing Surface tools" \
            emerge --quiet --autounmask-write --autounmask-continue "${pkgs[@]}"
    fi

    # Enable iptsd service
    if [[ "${ENABLE_IPTSD:-no}" == "yes" ]]; then
        if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
            try "Enabling iptsd" systemctl enable iptsd
        else
            ewarn "iptsd requires systemd — touchscreen daemon will NOT auto-start on OpenRC"
            ewarn "You can start it manually: /usr/bin/iptsd"
        fi
    fi

    einfo "Surface tools installed"
}

# install_fingerprint_tools — Install fprintd for fingerprint authentication
install_fingerprint_tools() {
    [[ "${ENABLE_FINGERPRINT:-no}" != "yes" ]] && return 0
    einfo "Installing fingerprint reader support..."
    try "Installing fprintd" emerge --quiet sys-auth/fprintd sys-auth/libfprint
    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        einfo "fprintd will be auto-activated via D-Bus on systemd"
    else
        ewarn "fprintd has limited OpenRC support — D-Bus activation may not work"
    fi
}

# install_thunderbolt_tools — Install bolt for Thunderbolt device management
install_thunderbolt_tools() {
    [[ "${ENABLE_THUNDERBOLT:-no}" != "yes" ]] && return 0
    einfo "Installing Thunderbolt management (bolt)..."
    try "Installing bolt" emerge --quiet sys-apps/bolt
    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        try "Enabling bolt" systemctl enable bolt
    else
        ewarn "bolt requires systemd — Thunderbolt authorization will not work on OpenRC"
    fi
}

# install_sensor_tools — Install iio-sensor-proxy for IIO sensors
install_sensor_tools() {
    [[ "${ENABLE_SENSORS:-no}" != "yes" ]] && return 0
    einfo "Installing IIO sensor proxy..."
    try "Installing iio-sensor-proxy" emerge --quiet gnome-extra/iio-sensor-proxy
    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        einfo "iio-sensor-proxy auto-started via systemd/udev"
    else
        ewarn "iio-sensor-proxy requires systemd for automatic startup"
    fi
}

# install_wwan_tools — Install ModemManager for WWAN LTE modem support
install_wwan_tools() {
    [[ "${ENABLE_WWAN:-no}" != "yes" ]] && return 0
    einfo "Installing WWAN LTE modem support..."
    try "Installing ModemManager" emerge --quiet net-misc/modemmanager
    try "Installing libmbim" emerge --quiet net-libs/libmbim
    try "Installing libqmi" emerge --quiet net-libs/libqmi
    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        try "Enabling ModemManager" systemctl enable ModemManager
    else
        try "Enabling ModemManager" rc-update add modemmanager default
    fi
    ewarn "Note: Intel XMM7360 requires ModemManager >= 1.26 for full support."
    ewarn "If the modem does not work, the FCC lock may need to be released"
    ewarn "(some laptops require initial activation under Windows)."
}

# setup_rog_overlay — Enable the zGentoo overlay for ASUS ROG tools
setup_rog_overlay() {
    if [[ "${ENABLE_ASUSCTL:-no}" != "yes" ]]; then
        return 0
    fi

    einfo "Enabling zGentoo overlay for ASUS ROG tools..."

    # zGentoo uses git for sync — ensure git is installed
    if ! command -v git &>/dev/null; then
        try "Installing dev-vcs/git" emerge --quiet dev-vcs/git
    fi

    # Ensure eselect-repository is available
    if ! eselect repository list &>/dev/null; then
        try "Installing eselect-repository" emerge --quiet app-eselect/eselect-repository
    fi

    try "Enabling zGentoo overlay" eselect repository enable zgentoo
    try "Syncing zGentoo overlay" emerge --sync zgentoo
}

# install_rog_tools — Install asusctl and supergfxctl from zGentoo overlay
install_rog_tools() {
    if [[ "${ENABLE_ASUSCTL:-no}" != "yes" ]]; then
        return 0
    fi

    einfo "Installing ASUS ROG tools (asusctl, supergfxctl)..."

    # Accept ~amd64 keywords
    mkdir -p /etc/portage/package.accept_keywords
    {
        echo "sys-power/asusctl ~amd64"
        echo "sys-power/supergfxctl ~amd64"
    } > /etc/portage/package.accept_keywords/asusctl

    try "Installing asusctl + supergfxctl" \
        emerge --quiet --autounmask-write --autounmask-continue \
        sys-power/asusctl sys-power/supergfxctl

    # Enable systemd services (asusctl requires systemd)
    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        try "Enabling asusd" systemctl enable asusd
        try "Enabling supergfxd" systemctl enable supergfxd
    else
        ewarn "asusctl/supergfxctl require systemd — services not enabled"
    fi

    einfo "ASUS ROG tools installed"
}

# install_extra_packages — Install user-selected extra packages
install_extra_packages() {
    # Enable GURU repo if requested (before installing packages)
    setup_guru_repository

    # Install Hyprland ecosystem if requested
    install_hyprland_ecosystem

    # Install noctalia-shell if requested
    install_noctalia_shell

    # Enable ROG overlay and install tools if requested
    setup_rog_overlay
    install_rog_tools

    # Enable Surface overlay and install tools if requested
    setup_surface_overlay
    install_surface_tools

    # Install peripheral tools if requested
    install_fingerprint_tools
    install_thunderbolt_tools
    install_sensor_tools
    install_wwan_tools

    if [[ -z "${EXTRA_PACKAGES:-}" ]]; then
        einfo "No extra packages to install"
        return 0
    fi

    # Package-specific USE flags
    local pkg
    for pkg in ${EXTRA_PACKAGES}; do
        case "${pkg}" in
            media-libs/libv4l)
                mkdir -p /etc/portage/package.use
                grep -qxF "media-libs/libv4l utils" /etc/portage/package.use/v4l 2>/dev/null || \
                    echo "media-libs/libv4l utils" >> /etc/portage/package.use/v4l
                ;;
        esac
    done

    einfo "Installing extra packages: ${EXTRA_PACKAGES}"
    for pkg in ${EXTRA_PACKAGES}; do
        # Validate package name (category/name format or simple name)
        if [[ ! "${pkg}" =~ ^[a-zA-Z0-9][a-zA-Z0-9_./-]*$ ]]; then
            ewarn "Skipping invalid package name: ${pkg}"
            continue
        fi
        try "Installing ${pkg}" emerge --quiet "${pkg}"
    done
}
