#!/usr/bin/env bash
# system.sh — fstab, locale, timezone, hostname, keymap, users, finalization
source "${LIB_DIR}/protection.sh"

# --- Timezone ---

system_set_timezone() {
    local tz="${TIMEZONE:-UTC}"
    einfo "Setting timezone: ${tz}"

    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        try "Setting timezone" ln -sf "/usr/share/zoneinfo/${tz}" /etc/localtime
        [[ -e /dev/rtc ]] && { try "Hardware clock" hwclock --systohc 2>/dev/null || true; }
    else
        echo "${tz}" > /etc/timezone
        try "Configuring timezone" emerge --config sys-libs/timezone-data
    fi
}

# --- Locale ---

system_set_locale() {
    local locale="${LOCALE:-en_US.UTF-8}"
    einfo "Setting locale: ${locale}"

    # Generate locale
    local locale_gen="/etc/locale.gen"
    {
        echo "# Generated by ${INSTALLER_NAME}"
        echo "${locale} UTF-8"
        # Always include en_US as fallback
        if [[ "${locale}" != "en_US.UTF-8" ]]; then
            echo "en_US.UTF-8 UTF-8"
        fi
    } > "${locale_gen}"

    try "Generating locales" locale-gen

    # Set system locale (eselect uses "utf8" not "UTF-8")
    local eselect_locale="${locale/UTF-8/utf8}"
    try "Setting system locale" eselect locale set "${eselect_locale}"

    # Update environment files for next boot.
    # Do NOT source /etc/profile — profile.d scripts may reference unset
    # variables which kills the installer under set -u (expansion errors
    # bypass || true). Also avoids resetting PATH and LANG mid-install.
    env-update 2>/dev/null || true
}

# --- Hostname ---

system_set_hostname() {
    local hostname="${HOSTNAME:-gentoo}"

    # Validate hostname (RFC 1123: alphanumeric + hyphens, no leading/trailing hyphen)
    if [[ ! "${hostname}" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$ ]]; then
        ewarn "Invalid hostname '${hostname}', falling back to 'gentoo'"
        hostname="gentoo"
    fi

    einfo "Setting hostname: ${hostname}"

    # Always write /etc/hostname (used by systemd, read by many tools)
    echo "${hostname}" > /etc/hostname

    if [[ "${INIT_SYSTEM:-systemd}" == "openrc" ]]; then
        # OpenRC also needs /etc/conf.d/hostname
        cat > /etc/conf.d/hostname << 'HOSTEOF'
hostname="PLACEHOLDER"
HOSTEOF
        sed -i "s/PLACEHOLDER/${hostname}/" /etc/conf.d/hostname
    fi

    # Update /etc/hosts
    cat > /etc/hosts << HOSTSEOF
# /etc/hosts
127.0.0.1   localhost
::1         localhost
127.0.1.1   ${hostname}.localdomain ${hostname}
HOSTSEOF
}

# --- Keymap ---

system_set_keymap() {
    local keymap="${KEYMAP:-us}"
    einfo "Setting keymap: ${keymap}"

    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        mkdir -p /etc/vconsole.conf.d
        cat > /etc/vconsole.conf << VCEOF
KEYMAP=${keymap}
VCEOF
    else
        cat > /etc/conf.d/keymaps << KMEOF
keymap="${keymap}"
windowkeys="YES"
extended_keymaps=""
dumpkeys_charset=""
fix_euro="NO"
KMEOF
    fi
}

# --- fstab ---

generate_fstab() {
    einfo "Generating /etc/fstab..."

    local fstab="/etc/fstab"
    local fs="${FILESYSTEM:-ext4}"

    {
        echo "# /etc/fstab"
        echo "# Generated by ${INSTALLER_NAME} v${INSTALLER_VERSION}"
        echo "#"
        echo "# <fs>                                  <mountpoint>  <type>  <opts>                                  <dump/pass>"

        # Root filesystem
        local root_uuid
        root_uuid=$(get_uuid "${ROOT_PARTITION}")
        if [[ -n "${root_uuid}" ]]; then
            case "${fs}" in
                btrfs)
                    echo "UUID=${root_uuid}   /             btrfs   subvol=@,compress=zstd,noatime,defaults  0 1"
                    # Additional subvolumes
                    if [[ -n "${BTRFS_SUBVOLUMES:-}" ]]; then
                        local IFS=':'
                        local -a parts
                        read -ra parts <<< "${BTRFS_SUBVOLUMES}"
                        local idx
                        for (( idx = 0; idx < ${#parts[@]}; idx += 2 )); do
                            local subvol="${parts[$idx]}"
                            local mpoint="${parts[$((idx + 1))]}"
                            [[ "${subvol}" == "@" ]] && continue
                            echo "UUID=${root_uuid}   ${mpoint}          btrfs   subvol=${subvol},compress=zstd,noatime,defaults  0 2"
                        done
                    fi
                    ;;
                ext4)
                    echo "UUID=${root_uuid}   /             ext4    noatime,defaults        0 1"
                    ;;
                xfs)
                    echo "UUID=${root_uuid}   /             xfs     noatime,defaults        0 1"
                    ;;
            esac
        else
            echo "${ROOT_PARTITION}              /             ${fs}     noatime,defaults        0 1"
        fi

        # ESP
        local esp_uuid
        esp_uuid=$(get_uuid "${ESP_PARTITION}")
        if [[ -n "${esp_uuid}" ]]; then
            echo "UUID=${esp_uuid}   /efi          vfat    noatime,defaults        0 2"
        else
            echo "${ESP_PARTITION}              /efi          vfat    noatime,defaults        0 2"
        fi

        # Swap partition
        if [[ "${SWAP_TYPE:-}" == "partition" && -n "${SWAP_PARTITION:-}" ]]; then
            local swap_uuid
            swap_uuid=$(get_uuid "${SWAP_PARTITION}")
            if [[ -n "${swap_uuid}" ]]; then
                echo "UUID=${swap_uuid}   none          swap    sw              0 0"
            else
                echo "${SWAP_PARTITION}              none          swap    sw              0 0"
            fi
        fi

        # tmpfs for /tmp
        echo "tmpfs                                   /tmp          tmpfs   defaults,nosuid,nodev   0 0"

    } > "${fstab}"

    einfo "fstab generated"
}

# install_filesystem_tools — Install tools for the selected filesystem
install_filesystem_tools() {
    local fs="${FILESYSTEM:-ext4}"
    einfo "Installing filesystem tools for ${fs}..."

    case "${fs}" in
        ext4)
            try "Installing e2fsprogs" emerge --quiet sys-fs/e2fsprogs
            ;;
        btrfs)
            try "Installing btrfs-progs" emerge --quiet sys-fs/btrfs-progs
            ;;
        xfs)
            try "Installing xfsprogs" emerge --quiet sys-fs/xfsprogs
            ;;
    esac

    # Always install dosfstools for ESP
    try "Installing dosfstools" emerge --quiet sys-fs/dosfstools
}

# --- Users ---

system_create_users() {
    einfo "Creating users..."

    # Set root password (pipe hash to avoid exposure in process list)
    if [[ -n "${ROOT_PASSWORD_HASH:-}" ]]; then
        try "Setting root password" \
            bash -c 'echo "root:$1" | chpasswd -e' -- "${ROOT_PASSWORD_HASH}"
    fi

    # Create regular user
    if [[ -n "${USERNAME:-}" ]]; then
        local groups="${USER_GROUPS:-wheel,audio,video,usb,input}"

        # Filter out groups that don't exist on the target system
        local valid_groups=""
        local g
        IFS=',' read -ra _groups <<< "${groups}"
        for g in "${_groups[@]}"; do
            if getent group "${g}" &>/dev/null; then
                valid_groups+="${valid_groups:+,}${g}"
            else
                ewarn "Group '${g}' does not exist, skipping"
            fi
        done
        groups="${valid_groups:-wheel}"

        try "Creating user ${USERNAME}" \
            useradd -m -G "${groups}" -s /bin/bash "${USERNAME}"

        if [[ -n "${USER_PASSWORD_HASH:-}" ]]; then
            try "Setting user password" \
                bash -c 'echo "$1:$2" | chpasswd -e' -- "${USERNAME}" "${USER_PASSWORD_HASH}"
        fi

        # Setup sudo
        try "Installing sudo" emerge --quiet app-admin/sudo

        # Allow wheel group to use sudo
        mkdir -p /etc/sudoers.d
        echo "%wheel ALL=(ALL:ALL) ALL" > /etc/sudoers.d/wheel
        chmod 0440 /etc/sudoers.d/wheel

        einfo "User ${USERNAME} created with groups: ${groups}"
    fi

}

# --- Finalization ---

system_finalize() {
    einfo "Finalizing system..."

    # Update environment files for next boot (same as in system_set_locale)
    try "Updating environment" env-update

    # Generate machine-id
    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        if [[ ! -f /etc/machine-id ]] || [[ ! -s /etc/machine-id ]]; then
            try "Generating machine-id" systemd-machine-id-setup
        fi
    fi

    # Install and enable SSH server (if requested)
    if [[ "${ENABLE_SSH:-yes}" == "yes" ]]; then
        try "Installing OpenSSH" emerge --quiet net-misc/openssh
        if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
            try "Enabling sshd" systemctl enable sshd
        else
            try "Enabling sshd" rc-update add sshd default
        fi
    fi

    # NTP time sync. Systemd ships timesyncd as part of base; OpenRC ships
    # nothing — first emerge --sync after a bad clock fails SSL handshake.
    if [[ "${INIT_SYSTEM:-systemd}" == "openrc" ]]; then
        try "Installing chrony" emerge --quiet net-misc/chrony
        try "Enabling chronyd" rc-update add chronyd default
        # Pull initial offset on boot before chronyd starts disciplining
        rc-update add swclock boot 2>/dev/null || true
    fi

    # Enable default systemd services
    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        try "Enabling default systemd services" \
            systemctl preset-all --preset-mode=enable-only
    fi

    # Enable SSD TRIM timer (essential for SSD/NVMe longevity and performance)
    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        systemctl enable fstrim.timer 2>/dev/null || true
        einfo "SSD TRIM timer enabled (weekly)"
    else
        # OpenRC: install fstrim cron job
        if command -v crontab &>/dev/null; then
            (crontab -l 2>/dev/null; echo "0 3 * * 0 /sbin/fstrim -a") | sort -u | crontab - 2>/dev/null || true
            einfo "SSD TRIM cron job added (weekly)"
        fi
    fi

    # Install power management for laptops
    if [[ -d /sys/class/power_supply/BAT0 ]] || [[ -d /sys/class/power_supply/BAT1 ]]; then
        einfo "Battery detected — installing power management..."
        if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
            try "Installing power-profiles-daemon" \
                emerge --quiet --keep-going sys-power/power-profiles-daemon || true
            systemctl enable power-profiles-daemon 2>/dev/null || true
        else
            try "Installing TLP" \
                emerge --quiet --keep-going app-laptop/tlp || true
            rc-update add tlp default 2>/dev/null || true
        fi
        # Install thermald for Intel CPUs
        if grep -qi 'GenuineIntel' /proc/cpuinfo 2>/dev/null; then
            try "Installing thermald" \
                emerge --quiet --keep-going sys-power/thermald || true
            if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
                systemctl enable thermald 2>/dev/null || true
            fi
        fi
        einfo "Power management installed"
    fi

    # Lenovo Legion: per-key RGB, fan curves, power/conservation mode are
    # driven by the out-of-tree lenovo-legion-laptop module — no ebuild in
    # the main tree or GURU (same situation as GPD's fan daemon). Write a
    # POST-INSTALL note so the user knows it needs manual setup, instead of
    # silently shipping without RGB/fan control.
    if grep -qi 'LENOVO' /sys/class/dmi/id/sys_vendor 2>/dev/null && \
       { grep -qi 'Legion' /sys/class/dmi/id/product_family 2>/dev/null || \
         grep -qi 'Legion' /sys/class/dmi/id/product_name 2>/dev/null; }; then
        einfo "Lenovo Legion detected — writing POST-INSTALL note"
        mkdir -p /root
        local lnotes=/root/POST-INSTALL-NOTES.txt
        touch "${lnotes}"; chmod 0600 "${lnotes}"
        local legion_model
        legion_model=$(cat /sys/class/dmi/id/product_version 2>/dev/null) || legion_model="Legion"
        cat >> "${lnotes}" << LEGIONEOF

=== Lenovo Legion control (${legion_model}) ===

Per-key RGB keyboard, custom fan curves, power/performance modes and
battery conservation mode need the out-of-tree lenovo-legion-laptop
kernel module — there is no Gentoo ebuild yet. The system works without
it (fans on firmware defaults), but those features are unavailable until
you install it manually:

  # emerge --ask sys-kernel/dkms
  git clone https://github.com/johnfanv2/LenovoLegionLinux.git
  cd LenovoLegionLinux/kernel_module
  sudo make dkms-install      # builds + registers via DKMS
  sudo modprobe legion-laptop

Userspace (GUI/CLI for fan curves, RGB, power modes):
  https://github.com/johnfanv2/LenovoLegionLinux  (LenovoLegionLinux app)

AMD Legion: amd_pstate is active on modern kernels; for finer control
add 'amd_pstate=active' to GRUB_CMDLINE_LINUX_DEFAULT in /etc/default/grub
and run grub-mkconfig -o /boot/grub/grub.cfg.

LEGIONEOF
    fi

    # HP Omen: per-key RGB and aggressive fan curves need out-of-tree
    # modules with no Gentoo ebuild (hp-omen-linux-module + omen-fan) —
    # same situation as Legion. hp-wmi (in-kernel) only gives the 3-step
    # platform_profile. Without a note the user's gaming laptop ships
    # with no RGB and firmware-default fans (throttling / loud).
    if grep -qiE 'HP|Hewlett-Packard' /sys/class/dmi/id/sys_vendor 2>/dev/null && \
       { grep -qi 'OMEN' /sys/class/dmi/id/product_family 2>/dev/null || \
         grep -qi 'OMEN' /sys/class/dmi/id/product_name 2>/dev/null; }; then
        einfo "HP Omen detected — writing POST-INSTALL note"
        mkdir -p /root
        local onotes=/root/POST-INSTALL-NOTES.txt
        touch "${onotes}"; chmod 0600 "${onotes}"
        local omen_model
        omen_model=$(cat /sys/class/dmi/id/product_name 2>/dev/null) || omen_model="OMEN"
        cat >> "${onotes}" << OMENEOF

=== HP Omen control (${omen_model}) ===

Function keys, keyboard backlight and the thermal platform_profile work
via the in-kernel hp-wmi driver:
  cat /sys/firmware/acpi/platform_profile_choices
  echo performance | sudo tee /sys/firmware/acpi/platform_profile

Per-key RGB and custom fan curves need out-of-tree modules — no Gentoo
ebuild exists yet:

  # emerge --ask sys-kernel/dkms
  git clone https://github.com/pelrun/hp-omen-linux-module.git
  cd hp-omen-linux-module && sudo make dkms-install
  sudo modprobe hp-wmi    # then /sys/devices/platform/hp-wmi/rgb_zones/*

  # Fan control daemon (custom curves):
  git clone https://github.com/alou-S/omen-fan.git
  # follow its README (Python; installs an omen-fan systemd service)

power-profiles-daemon (already installed) maps onto platform_profile, so
GNOME/KDE power modes will switch HP performance/quiet out of the box.

OMENEOF
    fi

    # Intel IPU6 MIPI camera (modern ThinkPad X1 / Dell / HP): kernel side
    # is force-added and PipeWire was built with libcamera, but the firmware
    # path and an apps-compatibility shim still warrant a note.
    if lspci -nn 2>/dev/null | grep -qiE '\[8086:(7d19|9a19|465d|a75d|645d|7d99)\]|image (signal )?process'; then
        einfo "Intel IPU6 camera detected — writing POST-INSTALL note"
        mkdir -p /root
        local inotes=/root/POST-INSTALL-NOTES.txt
        touch "${inotes}"; chmod 0600 "${inotes}"
        cat >> "${inotes}" << 'IPU6EOF'

=== Intel IPU6 MIPI camera ===

This laptop's webcam is an Intel IPU6 MIPI device, not a USB UVC cam.
The installer enabled the in-kernel IPU6/INT3472/VSC drivers + common
sensors and built PipeWire with the libcamera plugin. After first boot:

  1. Firmware: ships in sys-kernel/linux-firmware (intel/ipu/). If the
     camera is dead, ensure linux-firmware is recent and the sensor
     module loaded:  dmesg | grep -iE 'ipu6|ov02c10|ov2740|hi556|int3472'
  2. Test with libcamera:  cam -l   (lists cameras),  qcam  (preview)
  3. PipeWire exposes it to Wayland/Pipewire-aware apps automatically
     (KDE/GNOME camera, Firefox via PipeWire). Verify:  wpctl status
  4. Apps that demand a classic /dev/video0 (some Electron/Chromium,
     Zoom) need a v4l2 shim:
       emerge --ask media-video/v4l2loopback
       # plus a libcamera->v4l2 bridge (v4l2-relayd) — see the
       # Gentoo wiki "IPU6" / linux-intel-ipu6 docs.
  5. Older mainline (< ~6.10) lacks the in-tree IPU6 driver — then use
     the out-of-tree intel-ipu6-dkms + ipu6-camera-bins (Gentoo wiki).

IPU6EOF
    fi

    # Apple Mac (Intel): Broadcom WiFi often needs the proprietary wl driver
    # and/or firmware extracted from macOS; the bootloader was installed to
    # the removable path. T2 Macs are not really supported. Tell the user.
    if [[ "${APPLE_DETECTED:-0}" == "1" ]]; then
        einfo "Apple Mac detected — writing POST-INSTALL note"
        mkdir -p /root
        local anotes=/root/POST-INSTALL-NOTES.txt
        touch "${anotes}"; chmod 0600 "${anotes}"
        cat >> "${anotes}" << APPLEEOF

=== Apple Mac (${APPLE_MODEL:-Intel Mac}) ===

GRUB was installed to the removable-media path (\\EFI\\BOOT\\BOOTX64.EFI)
because Apple firmware does not persist normal UEFI boot entries. If the
Mac still boots straight into macOS, hold Option (Alt) at chime and pick
the EFI Boot volume; optionally bless it from macOS.

Wi-Fi (Broadcom):
  - BCM43602 / BCM4364: brcmfmac (in-kernel). Firmware ships in
    sys-kernel/linux-firmware; if Wi-Fi stays down, the firmware may
    need extracting from macOS (see linux-wifi / t2linux wiki).
  - BCM4360 (most 2013-2017 MacBook Pro): needs the proprietary driver
      # echo "net-wireless/broadcom-sta ~amd64" >> /etc/portage/package.accept_keywords/broadcom
      # emerge --ask net-wireless/broadcom-sta
    Use USB tethering / a USB Wi-Fi dongle for the first emerge.

Other Mac bits not handled by the installer: apple-gmux/vga_switcheroo
(dual-GPU MBP), facetimehd (FaceTime camera), applesmc (fans/keyboard
backlight) — all out-of-tree, install manually if needed.
APPLEEOF
        if [[ "${APPLE_T2_DETECTED:-0}" == "1" ]]; then
            cat >> "${anotes}" << 'T2EOF'

*** Apple T2 chip: NOT SUPPORTED by this installer. The internal SSD and
keyboard need the out-of-tree apple-bce module + t2linux kernel. If you
got this far the install likely used external media. See t2linux.org. ***
T2EOF
        fi
    fi

    # Install cpuid2cpuflags and update make.conf
    portage_install_cpuflags

    # Clean up downloaded source tarballs (can reclaim 1-3 GB)
    if command -v eclean-dist &>/dev/null; then
        einfo "Cleaning up distfiles..."
        eclean-dist --deep &>/dev/null || true
    else
        # eclean-dist not available (part of gentoolkit), clean manually
        rm -rf /var/cache/distfiles/* 2>/dev/null || true
    fi

    # Clean up
    checkpoint_clear
    rm -f /tmp/gentoo-installer.conf

    einfo "System finalization complete"
}
