#!/usr/bin/env bash
# system.sh — fstab, locale, timezone, hostname, keymap, users, finalization
source "${LIB_DIR}/protection.sh"

# --- Timezone ---

system_set_timezone() {
    local tz="${TIMEZONE:-UTC}"
    einfo "Setting timezone: ${tz}"

    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        try "Setting timezone" ln -sf "/usr/share/zoneinfo/${tz}" /etc/localtime
        try "Hardware clock" hwclock --systohc 2>/dev/null || true
    else
        echo "${tz}" > /etc/timezone
        try "Configuring timezone" emerge --config sys-libs/timezone-data
    fi
}

# --- Locale ---

system_set_locale() {
    local locale="${LOCALE:-en_US.UTF-8}"
    einfo "Setting locale: ${locale}"

    # Generate locale
    local locale_gen="/etc/locale.gen"
    {
        echo "# Generated by ${INSTALLER_NAME}"
        echo "${locale} UTF-8"
        # Always include en_US as fallback
        if [[ "${locale}" != "en_US.UTF-8" ]]; then
            echo "en_US.UTF-8 UTF-8"
        fi
    } > "${locale_gen}"

    try "Generating locales" locale-gen

    # Set system locale (eselect uses "utf8" not "UTF-8")
    local eselect_locale="${locale/UTF-8/utf8}"
    try "Setting system locale" eselect locale set "${eselect_locale}"

    # Update environment
    env-update 2>/dev/null || true
    # shellcheck disable=SC1091
    source /etc/profile 2>/dev/null || true
}

# --- Hostname ---

system_set_hostname() {
    local hostname="${HOSTNAME:-gentoo}"
    einfo "Setting hostname: ${hostname}"

    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        echo "${hostname}" > /etc/hostname
    else
        # OpenRC
        cat > /etc/conf.d/hostname << HOSTEOF
hostname="${hostname}"
HOSTEOF
    fi

    # Update /etc/hosts
    cat > /etc/hosts << HOSTSEOF
# /etc/hosts
127.0.0.1   localhost
::1         localhost
127.0.1.1   ${hostname}.localdomain ${hostname}
HOSTSEOF
}

# --- Keymap ---

system_set_keymap() {
    local keymap="${KEYMAP:-us}"
    einfo "Setting keymap: ${keymap}"

    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        mkdir -p /etc/vconsole.conf.d
        cat > /etc/vconsole.conf << VCEOF
KEYMAP=${keymap}
VCEOF
    else
        cat > /etc/conf.d/keymaps << KMEOF
keymap="${keymap}"
windowkeys="YES"
extended_keymaps=""
dumpkeys_charset=""
fix_euro="NO"
KMEOF
    fi
}

# --- fstab ---

generate_fstab() {
    einfo "Generating /etc/fstab..."

    local fstab="/etc/fstab"
    local fs="${FILESYSTEM:-ext4}"

    {
        echo "# /etc/fstab"
        echo "# Generated by ${INSTALLER_NAME} v${INSTALLER_VERSION}"
        echo "#"
        echo "# <fs>                                  <mountpoint>  <type>  <opts>                                  <dump/pass>"

        # Root filesystem
        local root_uuid
        root_uuid=$(get_uuid "${ROOT_PARTITION}")
        if [[ -n "${root_uuid}" ]]; then
            case "${fs}" in
                btrfs)
                    echo "UUID=${root_uuid}   /             btrfs   subvol=@,compress=zstd,noatime,defaults  0 1"
                    # Additional subvolumes
                    if [[ -n "${BTRFS_SUBVOLUMES:-}" ]]; then
                        local IFS=':'
                        local -a parts
                        read -ra parts <<< "${BTRFS_SUBVOLUMES}"
                        local idx
                        for (( idx = 0; idx < ${#parts[@]}; idx += 2 )); do
                            local subvol="${parts[$idx]}"
                            local mpoint="${parts[$((idx + 1))]}"
                            [[ "${subvol}" == "@" ]] && continue
                            echo "UUID=${root_uuid}   ${mpoint}          btrfs   subvol=${subvol},compress=zstd,noatime,defaults  0 2"
                        done
                    fi
                    ;;
                ext4)
                    echo "UUID=${root_uuid}   /             ext4    noatime,defaults        0 1"
                    ;;
                xfs)
                    echo "UUID=${root_uuid}   /             xfs     noatime,defaults        0 1"
                    ;;
            esac
        else
            echo "${ROOT_PARTITION}              /             ${fs}     noatime,defaults        0 1"
        fi

        # ESP
        local esp_uuid
        esp_uuid=$(get_uuid "${ESP_PARTITION}")
        if [[ -n "${esp_uuid}" ]]; then
            echo "UUID=${esp_uuid}   /efi          vfat    noatime,defaults        0 2"
        else
            echo "${ESP_PARTITION}              /efi          vfat    noatime,defaults        0 2"
        fi

        # Swap partition
        if [[ "${SWAP_TYPE:-}" == "partition" && -n "${SWAP_PARTITION:-}" ]]; then
            local swap_uuid
            swap_uuid=$(get_uuid "${SWAP_PARTITION}")
            if [[ -n "${swap_uuid}" ]]; then
                echo "UUID=${swap_uuid}   none          swap    sw              0 0"
            else
                echo "${SWAP_PARTITION}              none          swap    sw              0 0"
            fi
        fi

        # tmpfs for /tmp
        echo "tmpfs                                   /tmp          tmpfs   defaults,nosuid,nodev   0 0"

    } > "${fstab}"

    einfo "fstab generated"
}

# install_filesystem_tools — Install tools for the selected filesystem
install_filesystem_tools() {
    local fs="${FILESYSTEM:-ext4}"
    einfo "Installing filesystem tools for ${fs}..."

    case "${fs}" in
        ext4)
            try "Installing e2fsprogs" emerge --quiet sys-fs/e2fsprogs
            ;;
        btrfs)
            try "Installing btrfs-progs" emerge --quiet sys-fs/btrfs-progs
            ;;
        xfs)
            try "Installing xfsprogs" emerge --quiet sys-fs/xfsprogs
            ;;
    esac

    # Always install dosfstools for ESP
    try "Installing dosfstools" emerge --quiet sys-fs/dosfstools
}

# --- Users ---

system_create_users() {
    einfo "Creating users..."

    # Set root password
    if [[ -n "${ROOT_PASSWORD_HASH:-}" ]]; then
        try "Setting root password" \
            usermod -p "${ROOT_PASSWORD_HASH}" root
    fi

    # Create regular user
    if [[ -n "${USERNAME:-}" ]]; then
        local groups="${USER_GROUPS:-wheel,audio,video,usb,input}"

        try "Creating user ${USERNAME}" \
            useradd -m -G "${groups}" -s /bin/bash "${USERNAME}"

        if [[ -n "${USER_PASSWORD_HASH:-}" ]]; then
            try "Setting user password" \
                usermod -p "${USER_PASSWORD_HASH}" "${USERNAME}"
        fi

        # Setup sudo
        try "Installing sudo" emerge --quiet app-admin/sudo

        # Allow wheel group to use sudo
        mkdir -p /etc/sudoers.d
        echo "%wheel ALL=(ALL:ALL) ALL" > /etc/sudoers.d/wheel
        chmod 0440 /etc/sudoers.d/wheel

        einfo "User ${USERNAME} created with groups: ${groups}"
    fi

}

# --- Finalization ---

system_finalize() {
    einfo "Finalizing system..."

    # Update environment
    try "Updating environment" env-update
    # shellcheck disable=SC1091
    source /etc/profile 2>/dev/null || true

    # Generate machine-id
    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        if [[ ! -f /etc/machine-id ]] || [[ ! -s /etc/machine-id ]]; then
            try "Generating machine-id" systemd-machine-id-setup
        fi
    fi

    # Enable default systemd services
    if [[ "${INIT_SYSTEM:-systemd}" == "systemd" ]]; then
        try "Enabling default systemd services" \
            systemctl preset-all --preset-mode=enable-only
    fi

    # Install cpuid2cpuflags and update make.conf
    portage_install_cpuflags

    # Clean up
    checkpoint_clear
    rm -f /tmp/gentoo-installer.conf

    einfo "System finalization complete"
}
